// <auto-generated />
using System;
using LoggingExample.Business;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoggingExample.Business.LoggingExample.Business.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260610020806_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LoggingExample.Domain.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Rating = 5,
                            ReleaseDate = new DateTime(2001, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Shrek"
                        },
                        new
                        {
                            Id = 2,
                            Rating = 3,
                            ReleaseDate = new DateTime(2010, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            Rating = 4,
                            ReleaseDate = new DateTime(1999, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 4,
                            Rating = 5,
                            ReleaseDate = new DateTime(1968, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Gun"
                        },
                        new
                        {
                            Id = 5,
                            Rating = 5,
                            ReleaseDate = new DateTime(2011, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Puss in Boots"
                        },
                        new
                        {
                            Id = 6,
                            Rating = 5,
                            ReleaseDate = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Puss in Boots: The Last Wish"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
